using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using Microsoft.Data.Sqlite;

namespace RAG.Services;

public sealed record IndexedDocument(long Id, string Path, string FileName, int ChunkCount, DateTime IndexedUtc);

public sealed record SearchHit(string FileName, string Path, int PageNumber, string Text, float Score);

public sealed record FolderStats(int DocumentCount, int ChunkCount, DateTime? LastIndexedUtc);

/// <summary>
/// Raised when a database cannot be opened safely. Carries the inspection so the page can explain
/// what is wrong and offer the fix, rather than showing a bare SQLite error.
/// </summary>
public sealed class DatabaseUnsafeException(DatabaseInspection inspection)
    : Exception(inspection.Message ?? "The index database cannot be opened.")
{
    public DatabaseInspection Inspection { get; } = inspection;
}

/// <summary>
/// Stores chunks and their embeddings in SQLite, and answers "which chunks are most like this
/// question?".
///
/// One instance per dataset — the database path is fixed at construction, and
/// <see cref="VectorStoreProvider"/> hands out and caches them.
///
/// Search is a brute-force scan: every stored vector is compared against the query vector.
/// That sounds slow, but a dot product over 384 floats is trivial work — tens of thousands of
/// chunks are scored in a few milliseconds, which is nothing next to the LLM's response time.
/// A dedicated vector database only starts to earn its keep in the millions of chunks.
/// </summary>
public sealed class VectorStore
{
    /// <summary>Cache key standing in for "every folder in this dataset".</summary>
    private const string WholeDataset = "*";

    private readonly string _connectionString;
    private readonly ILogger _logger;
    private readonly int _maxCachedVectors;

    // Reading every embedding off disk for each question would dominate query time, so the
    // vectors for a folder are held in memory once loaded and dropped when that folder changes.
    // Folders bigger than _maxCachedVectors are never cached — see TryGetCache.
    private readonly ConcurrentDictionary<string, Lazy<VectorBlock>> _cache = new();

    public VectorStore(string databasePath, int maxCachedVectors, ILogger logger)
    {
        _logger = logger;
        _maxCachedVectors = maxCachedVectors;
        DatabasePath = databasePath;

        // Checked before the first connection is opened: replaying a foreign journal is what
        // destroys a database, and by the time SQLite reports "malformed" the damage is done.
        var inspection = DatabaseGuard.Inspect(databasePath);
        if (!inspection.IsSafeToOpen) throw new DatabaseUnsafeException(inspection);

        Directory.CreateDirectory(Path.GetDirectoryName(databasePath)!);

        _connectionString = new SqliteConnectionStringBuilder
        {
            DataSource = databasePath,
            Mode = SqliteOpenMode.ReadWriteCreate,
            Cache = SqliteCacheMode.Shared,
            Pooling = true
        }.ToString();

        Initialize();
    }

    public string DatabasePath { get; }

    public long DatabaseBytes
    {
        get
        {
            var file = new FileInfo(DatabasePath);
            return file.Exists ? file.Length : 0;
        }
    }

    /// <summary>Approximate memory currently held by cached vectors, for the metrics panel.</summary>
    public long CachedVectorBytes => _cache.Values
        .Where(entry => entry.IsValueCreated)
        .Sum(entry => (long)entry.Value.Count * entry.Value.Dimension * sizeof(float));

    /// <summary>Folder paths are the key everything hangs off, so they need one canonical form.</summary>
    public static string NormalizeFolder(string folder)
        => Path.TrimEndingDirectorySeparator(Path.GetFullPath(folder)).ToLowerInvariant();

    /// <summary>
    /// Bumped whenever the table definitions change. An older database is dropped and rebuilt
    /// rather than migrated: everything in it can be regenerated by re-indexing, and silently
    /// running against the wrong schema causes far more confusing problems.
    /// </summary>
    private const int SchemaVersion = 2;

    private void Initialize()
    {
        using var connection = Open();

        using (var version = connection.CreateCommand())
        {
            version.CommandText = "PRAGMA user_version;";
            var existing = Convert.ToInt32(version.ExecuteScalar());

            if (existing != 0 && existing != SchemaVersion)
            {
                _logger.LogWarning(
                    "Index schema is version {Existing}, this build expects {Expected}. Dropping the old index — re-index your folders.",
                    existing, SchemaVersion);

                using var drop = connection.CreateCommand();
                drop.CommandText = "DROP TABLE IF EXISTS Chunks; DROP TABLE IF EXISTS Documents;";
                drop.ExecuteNonQuery();
            }
        }

        using var command = connection.CreateCommand();
        command.CommandText =
            $"""
            PRAGMA journal_mode = WAL;

            CREATE TABLE IF NOT EXISTS Documents (
                Id           INTEGER PRIMARY KEY AUTOINCREMENT,
                Folder       TEXT    NOT NULL,
                Path         TEXT    NOT NULL,
                FileName     TEXT    NOT NULL,
                LastWriteUtc TEXT    NOT NULL,
                SizeBytes    INTEGER NOT NULL,
                PageCount    INTEGER NOT NULL,
                ChunkCount   INTEGER NOT NULL,
                IndexedUtc   TEXT    NOT NULL,

                -- Keyed on the pair, not on Path alone, so overlapping or nested folders can each
                -- hold their own copy of a shared file instead of stealing it from one another.
                UNIQUE (Folder, Path)
            );

            CREATE TABLE IF NOT EXISTS Chunks (
                Id         INTEGER PRIMARY KEY AUTOINCREMENT,
                DocumentId INTEGER NOT NULL REFERENCES Documents(Id) ON DELETE CASCADE,
                Ordinal    INTEGER NOT NULL,
                PageNumber INTEGER NOT NULL,
                Text       TEXT    NOT NULL,
                Embedding  BLOB    NOT NULL
            );

            CREATE INDEX IF NOT EXISTS IX_Documents_Folder ON Documents(Folder);
            CREATE INDEX IF NOT EXISTS IX_Chunks_DocumentId ON Chunks(DocumentId);

            PRAGMA user_version = {SchemaVersion};
            """;
        command.ExecuteNonQuery();
    }

    private SqliteConnection Open()
    {
        var connection = new SqliteConnection(_connectionString);
        connection.Open();

        using var pragma = connection.CreateCommand();
        pragma.CommandText = "PRAGMA foreign_keys = ON;";
        pragma.ExecuteNonQuery();

        return connection;
    }

    /// <summary>
    /// Folds the write-ahead log back into the database and truncates it to nothing.
    ///
    /// Called whenever the app is finished with a dataset, so an idle dataset folder never holds a
    /// journal. A journal left lying around is the thing that lets one index's <c>-wal</c> be
    /// mistaken for another's, which is exactly how a 3.5 GB index was once reduced to 6 MB.
    /// </summary>
    public void Checkpoint()
    {
        try
        {
            using var connection = Open();
            using var command = connection.CreateCommand();
            command.CommandText = "PRAGMA wal_checkpoint(TRUNCATE);";
            command.ExecuteNonQuery();
        }
        catch (SqliteException ex)
        {
            _logger.LogWarning(ex, "Could not checkpoint {Path}", DatabasePath);
        }
    }

    /// <summary>Checkpoints and releases pooled connections, so the file can be moved or deleted.</summary>
    public void Close()
    {
        Checkpoint();
        _cache.Clear();

        using var connection = new SqliteConnection(_connectionString);
        SqliteConnection.ClearPool(connection);
    }

    /// <summary>
    /// True if this exact file (same path, same timestamp, same size) is already indexed,
    /// which is what makes re-indexing a folder cheap.
    /// </summary>
    public bool IsUpToDate(string folder, string path, DateTime lastWriteUtc, long sizeBytes)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT 1 FROM Documents
            WHERE Folder = $folder AND Path = $path AND LastWriteUtc = $ts AND SizeBytes = $size
            LIMIT 1;
            """;
        command.Parameters.AddWithValue("$folder", folder);
        command.Parameters.AddWithValue("$path", path);
        command.Parameters.AddWithValue("$ts", lastWriteUtc.ToString("O"));
        command.Parameters.AddWithValue("$size", sizeBytes);

        return command.ExecuteScalar() is not null;
    }

    /// <summary>Replaces a document and all of its chunks in a single transaction.</summary>
    public void SaveDocument(
        string folder,
        string path,
        DateTime lastWriteUtc,
        long sizeBytes,
        int pageCount,
        IReadOnlyList<TextChunk> chunks,
        IReadOnlyList<float[]> embeddings)
    {
        if (chunks.Count != embeddings.Count)
            throw new ArgumentException("Chunk and embedding counts must match.", nameof(embeddings));

        using var connection = Open();
        using var transaction = connection.BeginTransaction();

        using (var delete = connection.CreateCommand())
        {
            delete.CommandText = "DELETE FROM Documents WHERE Folder = $folder AND Path = $path;";
            delete.Parameters.AddWithValue("$folder", folder);
            delete.Parameters.AddWithValue("$path", path);
            delete.ExecuteNonQuery();
        }

        long documentId;
        using (var insert = connection.CreateCommand())
        {
            insert.CommandText =
                """
                INSERT INTO Documents (Folder, Path, FileName, LastWriteUtc, SizeBytes, PageCount, ChunkCount, IndexedUtc)
                VALUES ($folder, $path, $name, $ts, $size, $pages, $chunks, $indexed);
                SELECT last_insert_rowid();
                """;
            insert.Parameters.AddWithValue("$folder", folder);
            insert.Parameters.AddWithValue("$path", path);
            insert.Parameters.AddWithValue("$name", Path.GetFileName(path));
            insert.Parameters.AddWithValue("$ts", lastWriteUtc.ToString("O"));
            insert.Parameters.AddWithValue("$size", sizeBytes);
            insert.Parameters.AddWithValue("$pages", pageCount);
            insert.Parameters.AddWithValue("$chunks", chunks.Count);
            insert.Parameters.AddWithValue("$indexed", DateTime.UtcNow.ToString("O"));

            documentId = (long)insert.ExecuteScalar()!;
        }

        using (var insertChunk = connection.CreateCommand())
        {
            insertChunk.CommandText =
                """
                INSERT INTO Chunks (DocumentId, Ordinal, PageNumber, Text, Embedding)
                VALUES ($doc, $ordinal, $page, $text, $embedding);
                """;

            var documentParameter = insertChunk.Parameters.Add("$doc", SqliteType.Integer);
            var ordinalParameter = insertChunk.Parameters.Add("$ordinal", SqliteType.Integer);
            var pageParameter = insertChunk.Parameters.Add("$page", SqliteType.Integer);
            var textParameter = insertChunk.Parameters.Add("$text", SqliteType.Text);
            var embeddingParameter = insertChunk.Parameters.Add("$embedding", SqliteType.Blob);

            for (var i = 0; i < chunks.Count; i++)
            {
                documentParameter.Value = documentId;
                ordinalParameter.Value = i;
                pageParameter.Value = chunks[i].PageNumber;
                textParameter.Value = chunks[i].Text;
                embeddingParameter.Value = ToBlob(embeddings[i]);
                insertChunk.ExecuteNonQuery();
            }
        }

        transaction.Commit();
        Invalidate(folder);
    }

    /// <summary>Drops indexed documents that no longer exist on disk (renamed, moved or deleted).</summary>
    public int RemoveMissingDocuments(string folder, IReadOnlySet<string> pathsOnDisk)
    {
        using var connection = Open();

        var stale = new List<string>();
        using (var select = connection.CreateCommand())
        {
            select.CommandText = "SELECT Path FROM Documents WHERE Folder = $folder;";
            select.Parameters.AddWithValue("$folder", folder);

            using var reader = select.ExecuteReader();
            while (reader.Read())
            {
                var path = reader.GetString(0);
                if (!pathsOnDisk.Contains(path)) stale.Add(path);
            }
        }

        if (stale.Count == 0) return 0;

        using var transaction = connection.BeginTransaction();
        using (var delete = connection.CreateCommand())
        {
            delete.CommandText = "DELETE FROM Documents WHERE Folder = $folder AND Path = $path;";
            delete.Parameters.AddWithValue("$folder", folder);
            var parameter = delete.Parameters.Add("$path", SqliteType.Text);
            foreach (var path in stale)
            {
                parameter.Value = path;
                delete.ExecuteNonQuery();
            }
        }
        transaction.Commit();

        Invalidate(folder);
        _logger.LogInformation("Removed {Count} document(s) that are no longer on disk.", stale.Count);
        return stale.Count;
    }

    public void ClearFolder(string folder)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText = "DELETE FROM Documents WHERE Folder = $folder;";
        command.Parameters.AddWithValue("$folder", folder);
        command.ExecuteNonQuery();

        Invalidate(folder);
    }

    /// <summary>Stats for one folder, or for the whole dataset when <paramref name="folder"/> is null.</summary>
    public FolderStats GetStats(string? folder)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText =
            $"""
            SELECT COUNT(*), COALESCE(SUM(ChunkCount), 0), MAX(IndexedUtc)
            FROM Documents {FolderFilter(folder, "")};
            """;
        AddFolder(command, folder);

        using var reader = command.ExecuteReader();
        if (!reader.Read()) return new FolderStats(0, 0, null);

        DateTime? lastIndexed = reader.IsDBNull(2)
            ? null
            : DateTime.Parse(reader.GetString(2), null, System.Globalization.DateTimeStyles.RoundtripKind);

        return new FolderStats(reader.GetInt32(0), reader.GetInt32(1), lastIndexed);
    }

    /// <summary>Every source folder this dataset holds, for the dataset contents list.</summary>
    public List<DatasetFolder> GetFolders()
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText =
            """
            SELECT Folder, COUNT(*), COALESCE(SUM(ChunkCount), 0), MAX(IndexedUtc)
            FROM Documents
            GROUP BY Folder
            ORDER BY Folder;
            """;

        var folders = new List<DatasetFolder>();
        using var reader = command.ExecuteReader();
        while (reader.Read())
        {
            folders.Add(new DatasetFolder(
                reader.GetString(0),
                reader.GetInt32(1),
                reader.GetInt32(2),
                reader.IsDBNull(3)
                    ? null
                    : DateTime.Parse(reader.GetString(3), null, System.Globalization.DateTimeStyles.RoundtripKind)));
        }

        return folders;
    }

    public List<IndexedDocument> GetDocuments(string? folder)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText =
            $"""
            SELECT Id, Path, FileName, ChunkCount, IndexedUtc
            FROM Documents {FolderFilter(folder, "")}
            ORDER BY FileName;
            """;
        AddFolder(command, folder);

        var documents = new List<IndexedDocument>();
        using var reader = command.ExecuteReader();
        while (reader.Read())
        {
            documents.Add(new IndexedDocument(
                reader.GetInt64(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetInt32(3),
                DateTime.Parse(reader.GetString(4), null, System.Globalization.DateTimeStyles.RoundtripKind)));
        }

        return documents;
    }

    /// <summary>
    /// Width of the stored vectors, or 0 when nothing is indexed yet. Compared against the query
    /// vector so a mismatched embedding model is reported rather than silently matching nothing.
    /// </summary>
    public int GetEmbeddingDimension(string? folder = null)
    {
        using var connection = Open();
        return GetDimension(connection, folder);
    }

    /// <summary>
    /// Scores every chunk against the query vector and returns the best matches. Pass null for
    /// <paramref name="folder"/> to search the whole dataset.
    ///
    /// Both sides are unit vectors, so the dot product is exactly the cosine similarity:
    /// 1.0 means "points in the same direction", 0.0 means unrelated.
    ///
    /// Two strategies, chosen by size:
    ///  - Small enough to cache: vectors are held in one contiguous float array and scanned in memory.
    ///  - Too large: vectors are streamed straight off disk and scored as they arrive, so a huge
    ///    index costs almost no memory instead of crashing on the first question.
    ///
    /// Either way only the chunk *text* for the winning handful is read, never all of it.
    /// </summary>
    public List<SearchHit> Search(string? folder, float[] queryEmbedding, int topK, float minScore)
    {
        var winners = new TopK(topK);

        var cache = TryGetCache(folder);
        if (cache is not null)
        {
            ScoreCached(cache, queryEmbedding, ref winners);
        }
        else
        {
            ScoreStreaming(folder, queryEmbedding, ref winners);
        }

        var ranked = winners.Drain(minScore);
        return ranked.Count == 0 ? [] : Hydrate(ranked);
    }

    private static void ScoreCached(VectorBlock block, float[] query, ref TopK winners)
    {
        if (block.Dimension != query.Length) return; // index built with a different embedding model

        var vectors = block.Vectors.AsSpan();

        for (int i = 0, offset = 0; i < block.Count; i++, offset += block.Dimension)
        {
            winners.Offer(block.ChunkIds[i], Dot(query, vectors.Slice(offset, block.Dimension)));
        }
    }

    private void ScoreStreaming(string? folder, float[] query, ref TopK winners)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText =
            $"""
            SELECT c.Id, c.Embedding
            FROM Chunks c
            JOIN Documents d ON d.Id = c.DocumentId
            {FolderFilter(folder, "d.")};
            """;
        AddFolder(command, folder);

        // One reusable buffer for the whole scan: reading a fresh byte[] per row would churn
        // gigabytes of garbage on a large index.
        var buffer = new byte[query.Length * sizeof(float)];

        using var reader = command.ExecuteReader();
        while (reader.Read())
        {
            var read = (int)reader.GetBytes(1, 0, buffer, 0, buffer.Length);
            if (read != buffer.Length) continue; // different embedding dimension; skip

            var vector = MemoryMarshal.Cast<byte, float>(buffer.AsSpan(0, read));
            winners.Offer(reader.GetInt64(0), Dot(query, vector));
        }
    }

    /// <summary>Loads the text and document details for the small set of chunks that actually won.</summary>
    private List<SearchHit> Hydrate(List<(long Id, float Score)> ranked)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();

        var parameterNames = ranked.Select((_, i) => $"$id{i}").ToArray();
        command.CommandText =
            $"""
             SELECT c.Id, d.FileName, d.Path, c.PageNumber, c.Text
             FROM Chunks c
             JOIN Documents d ON d.Id = c.DocumentId
             WHERE c.Id IN ({string.Join(", ", parameterNames)});
             """;

        for (var i = 0; i < ranked.Count; i++) command.Parameters.AddWithValue(parameterNames[i], ranked[i].Id);

        var byId = new Dictionary<long, SearchHit>(ranked.Count);
        using (var reader = command.ExecuteReader())
        {
            while (reader.Read())
            {
                var id = reader.GetInt64(0);
                byId[id] = new SearchHit(reader.GetString(1), reader.GetString(2), reader.GetInt32(3), reader.GetString(4), 0);
            }
        }

        // Re-apply the ranking order and attach each score.
        return ranked
            .Where(r => byId.ContainsKey(r.Id))
            .Select(r => byId[r.Id] with { Score = r.Score })
            .ToList();
    }

    // ---------- folder filtering ----------

    // Built as SQL text rather than a "$folder IS NULL OR ..." parameter so the whole-dataset case
    // is a clean table scan and the single-folder case still uses IX_Documents_Folder.
    private static string FolderFilter(string? folder, string prefix)
        => folder is null ? "" : $"WHERE {prefix}Folder = $folder";

    private static void AddFolder(SqliteCommand command, string? folder)
    {
        if (folder is not null) command.Parameters.AddWithValue("$folder", folder);
    }

    // ---------- vector cache ----------

    /// <summary>
    /// Drops the cache for a folder, and the whole-dataset cache with it — a change to any folder
    /// invalidates the combined block that folder is part of.
    /// </summary>
    private void Invalidate(string folder)
    {
        _cache.TryRemove(folder, out _);
        _cache.TryRemove(WholeDataset, out _);
    }

    /// <summary>
    /// Returns the cached vectors for a folder, building the cache on first use.
    /// Returns null when there are too many to cache, which switches Search to streaming.
    /// </summary>
    private VectorBlock? TryGetCache(string? folder)
    {
        var key = folder ?? WholeDataset;

        if (_cache.TryGetValue(key, out var existing)) return existing.Value;

        var count = CountChunks(folder);
        if (count > _maxCachedVectors)
        {
            _logger.LogInformation(
                "{Scope} has {Count} chunks, above the {Max} cache limit — searching straight from disk.",
                folder ?? "This dataset", count, _maxCachedVectors);
            return null;
        }

        // Lazy so that two simultaneous questions don't both build the cache.
        var lazy = _cache.GetOrAdd(key, _ => new Lazy<VectorBlock>(() => LoadVectors(folder)));
        return lazy.Value;
    }

    private int CountChunks(string? folder)
    {
        using var connection = Open();
        using var command = connection.CreateCommand();
        command.CommandText = $"SELECT COALESCE(SUM(ChunkCount), 0) FROM Documents {FolderFilter(folder, "")};";
        AddFolder(command, folder);

        return Convert.ToInt32(command.ExecuteScalar());
    }

    /// <summary>
    /// Loads every vector for a folder into one contiguous array.
    ///
    /// One big array rather than one array per chunk: it removes ~24 bytes of object header per
    /// chunk, keeps the scan sequential in memory, and avoids handing the GC a million small
    /// objects to trace. Chunk text is deliberately left on disk — it is by far the larger half.
    /// </summary>
    private VectorBlock LoadVectors(string? folder)
    {
        using var connection = Open();

        var count = CountChunks(folder);
        var dimension = GetDimension(connection, folder);

        if (count == 0 || dimension == 0) return VectorBlock.Empty;

        var block = new VectorBlock
        {
            Dimension = dimension,
            Vectors = new float[(long)count * dimension],
            ChunkIds = new long[count]
        };

        using var command = connection.CreateCommand();
        command.CommandText =
            $"""
            SELECT c.Id, c.Embedding
            FROM Chunks c
            JOIN Documents d ON d.Id = c.DocumentId
            {FolderFilter(folder, "d.")};
            """;
        AddFolder(command, folder);

        var bytes = new byte[dimension * sizeof(float)];
        var index = 0;

        using (var reader = command.ExecuteReader())
        {
            while (reader.Read() && index < count)
            {
                var read = (int)reader.GetBytes(1, 0, bytes, 0, bytes.Length);
                if (read != bytes.Length) continue;

                MemoryMarshal.Cast<byte, float>(bytes)
                    .CopyTo(block.Vectors.AsSpan(index * dimension, dimension));

                block.ChunkIds[index++] = reader.GetInt64(0);
            }
        }

        block.Count = index;

        _logger.LogInformation(
            "Cached {Count} vectors ({Megabytes} MB) for {Scope}.",
            index, index * dimension * sizeof(float) / (1024 * 1024), folder ?? "the whole dataset");

        return block;
    }

    private static int GetDimension(SqliteConnection connection, string? folder)
    {
        using var command = connection.CreateCommand();
        command.CommandText =
            $"""
            SELECT LENGTH(c.Embedding)
            FROM Chunks c
            JOIN Documents d ON d.Id = c.DocumentId
            {FolderFilter(folder, "d.")}
            LIMIT 1;
            """;
        AddFolder(command, folder);

        var result = command.ExecuteScalar();
        return result is null or DBNull ? 0 : Convert.ToInt32(result) / sizeof(float);
    }

    /// <summary>Reports whether a search is served from memory or streamed, for display in the UI.</summary>
    public string DescribeSearchMode(string? folder)
        => _cache.ContainsKey(folder ?? WholeDataset) || CountChunks(folder) <= _maxCachedVectors
            ? "in memory"
            : "streamed from disk";

    // ---------- scoring primitives ----------

    /// <summary>
    /// Dot product of two unit vectors, which is their cosine similarity.
    /// Uses the widest SIMD registers the CPU has, so this handles 8 or 16 floats per step
    /// instead of one.
    /// </summary>
    private static float Dot(ReadOnlySpan<float> a, ReadOnlySpan<float> b)
    {
        var width = System.Numerics.Vector<float>.Count;
        var accumulator = System.Numerics.Vector<float>.Zero;

        var i = 0;
        for (; i <= a.Length - width; i += width)
        {
            accumulator += new System.Numerics.Vector<float>(a.Slice(i, width))
                         * new System.Numerics.Vector<float>(b.Slice(i, width));
        }

        var sum = System.Numerics.Vector.Dot(accumulator, System.Numerics.Vector<float>.One);
        for (; i < a.Length; i++) sum += a[i] * b[i];

        return sum;
    }

    /// <summary>
    /// Keeps only the best K scores seen so far.
    ///
    /// Sorting every score would mean allocating and ordering a list as long as the whole index on
    /// every question. K is single digits, so a small insertion-sorted array is both faster and
    /// allocation-free.
    /// </summary>
    private struct TopK(int capacity)
    {
        private readonly long[] _ids = new long[capacity];
        private readonly float[] _scores = new float[capacity];
        private int _count = 0;

        public void Offer(long id, float score)
        {
            if (_count == _ids.Length && score <= _scores[_count - 1]) return;

            var position = _count < _ids.Length ? _count++ : _ids.Length - 1;

            while (position > 0 && _scores[position - 1] < score)
            {
                _scores[position] = _scores[position - 1];
                _ids[position] = _ids[position - 1];
                position--;
            }

            _scores[position] = score;
            _ids[position] = id;
        }

        public readonly List<(long Id, float Score)> Drain(float minScore)
        {
            var results = new List<(long, float)>(_count);
            for (var i = 0; i < _count; i++)
            {
                if (_scores[i] >= minScore) results.Add((_ids[i], _scores[i]));
            }
            return results;
        }
    }

    // Storing the floats as a raw byte blob keeps the database compact and the read path fast.
    private static byte[] ToBlob(float[] vector) => MemoryMarshal.AsBytes<float>(vector).ToArray();

    private sealed class VectorBlock
    {
        public static readonly VectorBlock Empty = new() { Vectors = [], ChunkIds = [] };

        public int Dimension { get; init; }
        public int Count { get; set; }
        public required float[] Vectors { get; init; }
        public required long[] ChunkIds { get; init; }
    }
}
